config/routes.rb
Rails.application.routes.draw do
  resources :wikis

  resources :charges, only: [:new, :create]

  resources :collaborators, only: [:create, :destroy]

  devise_for :users

  get 'about' => 'welcome#about'

  get 'search', to: 'search#search'

  post "users/downgrade" => "users#downgrade", :as => "downgrade"

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :wiki
  belongs_to :user

  def self.available(wiki, current_user)
    possible_collaborators = User.all.where.not(id: current_user.id)
    already_taken = wiki.collaborators.map{ |collaborator| User.find_by_id(collaborator.user_id)}
    possible_collaborators - already_taken
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :wikis, dependent: :destroy

  has_many :collaborators

  after_initialize :init

  enum role: [:standard, :premium, :admin]

  private
  def init
    self.add_role :standard
  end
end

app/models/wiki.rb
require 'elasticsearch/model'

class Wiki < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  belongs_to :user
  has_many :collaborators
  resourcify

  scope :visible_to, -> (user) { user ? all : where(private: false) }

  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['title^10', 'body']
          }
        },
        highlight: {
          pre_tags: ['<em>'],
          post_tags: ['</em>'],
          fields: {
            title: {},
            body: {}
          }
        }
      }
    )
  end

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :title, analyzer: 'english', index_options: 'offsets'
      indexes :body, analyzer: 'english'
    end
  end
end
Wiki.__elasticsearch__.client.indices.delete index: Wiki.index_name rescue nil

Wiki.__elasticsearch__.client.indices.create \
index: Wiki.index_name,
body: { settings: Wiki.settings.to_hash, mappings: Wiki.mappings.to_hash }
Wiki.import

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || wikis_path)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
    @user = current_user
    # Creates a Stripe Customer object, for associating
    # with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    # Where the real magic happens
    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the user_id in your app
      amount: 15_00,
      description: "Upgrade to Premium Membership - #{current_user.email}",
      currency: 'usd'
    )

    @user.add_role :premium

    flash[:notice] = "Thanks for upgrading your membership, #{current_user.email}!"
    redirect_to edit_user_registration_path

    # Stripe will send back CardErrors, with friendly messages
    # when something goes wrong.
    # This `rescue block` catches and displays those errors.
    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Premium Membership - #{current_user.email}",
      amount: 15_00
    }
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def create
    @collaborator = Collaborator.new(collaborator_params)
    @wiki = Wiki.find_by(id: params[:collaborator][:wiki_id])

    if @collaborator.save
      flash[:notice] = "Collaborator has been saved."
      redirect_to @wiki
    else
      flash[:alert] = "There was an error saving the collaborator. Please try again."
      render :show
    end
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])

    if @collaborator.destroy
      flash[:notice] = "Collaborator has been removed."
      redirect_to @collaborator.wiki
    else
      flash.now[:alert] = "There as an error removing the collaborator."
      redirect_to @collaborator.wiki
    end
  end

  private

  def collaborator_params
    params.require(:collaborator).permit(:user_id, :wiki_id)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if params[:q].nil?
      @wikis = []
    else
      @wikis = Wiki.search params[:q]
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def downgrade
    @user = current_user
    @user.remove_role :premium

    if @user.save
      wikis = @user.wikis
      wikis.update_all(private: false)
      flash[:notice] = "Your membership has been downgraded to standard."
      redirect_to root_path
    else
      flash.now[:alert] = "There was an error downgrading the account. Please try again."
      redirect_to edit_user_registration_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, except: [:index, :about]
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis =  policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    @all_collaborators = Collaborator.available(@wiki, current_user)
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki = current_user.wikis.build(wiki_params)
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @wiki.assign_attributes(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end

private

def wiki_params
  params.require(:wiki).permit(:title, :body, :private)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/wikis_helper.rb
module WikisHelper
  def user_is_authorized_for_wikis?
    current_user && current_user.admin?
  end
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Upgrade to Premium Membership!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
         <li><%= link_to "Home", root_path %></li>
         <li><%= link_to "About", about_path %></li>
         <li><%= link_to "Wikis", wikis_path %></li>
         <li><%= link_to "Search", search_path %></li>
      <div class="pull-right user-info">
        <% if user_signed_in? %>
          Signed in as: <strong><%= current_user.email %></strong> |
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
          <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </div>
      </ul>
    </div>
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash.now[:alert] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash.now[:alert] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
    </div>
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/search/search.html.erb
<h1>Wikis Search</h1>

<%= form_for search_path, method: :get do |f| %>
  <p>
    <%= f.label "Search for" %>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Go", name: nil %>
  </p>
<% end %>

<ul>
  <% @wikis.each do |wiki| %>
    <li>
      <h3>
        <%= link_to wiki.try(:highlight).try(:title) ? wiki.highlight.title[0].html_safe : wiki.title,
          controller: "wikis",
          action: "show",
          id: wiki._id%>
      </h3>
      <% if wiki.try(:highlight).try(:body) %>
        <% wiki.highlight.body.each do |snippet| %>
          <p><%= snippet.html_safe %>...</p>
        <% end %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/about.html.erb
<div class="well">
  <h3>Wikkr creates public and private Markdown-based wikis.</h3>
  <h4>Features:</h4>
  <ul>
    <li>Support admin, standard, and premium roles</li>
    <li>Create public wikis as a standard user</li>
    <li>Upgrade account using Stripe</li>
    <li>Create private wikis as a premium or admin user</li>
    <li>Add and remove collaborators for private wikis</li>
    <li>Render Markdown syntax using Redcarpet gem</li>
    <li>Search wikis using Elasticsearch</li>
  </ul>
  <h5><a href="https://github.com/lkang-pdx/blocipedia">GitHub Repo</a></h5>
</div>

<div class="columns">
  <ul class="price">
    <li class="header">Basic Plan</li>
    <li class="grey">FREE</li>
    <li>Free public wikis</li>
    <li class="grey"><%= link_to "Go Basic", new_user_registration_path, class: 'btn btn-primary btn-lg' %></li>
  </ul>
</div>
<div class="columns">
  <ul class="price">
    <li class="header-premium">Premium Plan</li>
    <li class="grey">$15<small>/year</small></li>
    <li>Unlimited private wikis</li>
    <li class="grey"><%= link_to "Go Premium", new_user_registration_path, class: 'btn btn-primary btn-lg' %></li>
  </ul>
</div>
<div class="columns">
  <ul class="price">
    <li class="header-platinum">Platinum Plan</li>
    <li class="grey">$30<small>/year</small></li>
    <li>Coming soon!</li>
    <li class="grey"><%= link_to "Go Platinum", new_user_registration_path, class: 'btn btn-primary btn-lg' %></li>
  </ul>
</div>

<script type="text/javascript">
    $(document).on("ready page:load", function () {
       scrutinize.report("About Page");
     })
</script>

app/views/welcome/index.html.erb
<div id='banner'>
  <div class='banner_content'>
    <h1>Wikkr</h1>
    <h3>Join the millions of people who rely on Wikkr<br>to capture off-the-cuff ideas.</h3>
    <p>
      <%= link_to "Sign Me Up", new_user_registration_path, class: 'button bt-primary' %>
    </p>
  </div>
</div>
<!-- <div id='bottom_cta'>
  <div class='wrapper'>
    <i class='fa fa-flash fa-3x'></i>
    <h2>Brainstorm Like a Boss</h2>
    <p>Collaborate seamlessly with coworkers from anywhere.</p>
    <p>
      <%= link_to "Sign Me Up", new_user_registration_path, class: 'button' %>
    </p>
  </div>
</div> -->
<footer>
  <p>Copyright &copy; 2017 Wikkr</p>
</footer>

app/views/wikis/_collaborators.html.erb
<%= form_for Collaborator.new do |f| %>
  <%= f.select(:user_id, @all_collaborators.collect{|w| [w.email, w.id]}) %>
  <%= f.hidden_field :wiki_id, value: @wiki.id %>
  <%= f.submit %>
<% end %>

app/views/wikis/_form.html.erb
<div class="row">
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
      <% if current_user.is_admin? || current_user.is_premium? %>
        <div class="form-group">
          <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Make private
          <% end %>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/_list.html.erb
<div>
  <% @wiki.collaborators.each do |collaborator| %>
    <h5><%= collaborator.user.email %> <%= link_to "", [collaborator], method: :delete, class: 'glyphicon glyphicon-remove-circle', data: {confirm: "Are you sure you want to delete this contributor?"} %></h5>
  <% end %>
</div>

app/views/wikis/edit.html.erb
<h1>Edit Post</h1>

<%= render partial: 'form', locals: { wiki: @wiki } %>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<%= link_to "New Wiki", new_wiki_path, class: 'btn btn-info' %>

<% @wikis.each do |wiki| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to markdown(wiki.title), wiki %>
      </h4>
    </div>
  </div>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<%= render partial: 'form', locals: { wiki: @wiki } %>

app/views/wikis/show.html.erb
<h1><%= markdown(@wiki.title) %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body) %></p>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <% if user_is_authorized_for_wikis? %>
    <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
    <% end %>
  </div>
</div>

<% if current_user.id == @wiki.user_id && @wiki.private %>
<h3>Available Collaborators</h3>
<div class="container">
  <%= render partial: 'collaborators' %>
</div>
<% end %>
<% if @wiki.private %>
<h3>Current Collaborators</h3>
<div class="container">
  <p><%= render partial: 'list' %></p>
</div>
<% end %>